spring.application.name=document_management_system

spring.datasource.url=jdbc:postgresql://localhost:5432/document_management_system
spring.datasource.username=postgres
spring.datasource.password=Tawade@300902
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=Tawade
spring.security.user.password=Tawade300902

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tawadeshubham10@gmail.com
spring.mail.password=fkxf xeig cuxs saki
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true