INSERT INTO authority_profiles (authority_id, authority_name, created_at)
VALUES
('0000', 'ROOT_ADMIN', CURRENT_TIMESTAMP),
('0001', 'ADMIN,SUPER_USER,USER', CURRENT_TIMESTAMP),
('0002', 'SUPER_USER,USER', CURRENT_TIMESTAMP),
('0003', 'ADMIN', CURRENT_TIMESTAMP),
('0004', 'ADMIN,USER', CURRENT_TIMESTAMP),
('0005', 'USER', CURRENT_TIMESTAMP);