INSERT INTO roles(role_id,role_name,created_at)
VALUES
('0000','ROOT_USER',CURRENT_TIMESTAMP),
('0001','ADMIN',CURRENT_TIMESTAMP),
('0002','SUPER_USER',CURRENT_TIMESTAMP),
('0003','USER',CURRENT_TIMESTAMP);