INSERT INTO status (status_id, description, created_at)
VALUES
('PSV', 'PAGE SAVED', CURRENT_TIMESTAMP),
('PPB', 'PAGE PUBLISHED', CURRENT_TIMESTAMP),
('PSA', 'PAGE SAVED ARCHIVED', CURRENT_TIMESTAMP),
('PPA', 'PAGE PUBLISHED ARCHIVED', CURRENT_TIMESTAMP),

('NAC', 'NOTEBOOK ACTIVE', CURRENT_TIMESTAMP),
('NAR', 'NOTEBOOK ARCHIVED', CURRENT_TIMESTAMP),

('UAC', 'USER ACTIVE', CURRENT_TIMESTAMP),
('UIA', 'USER INACTIVE', CURRENT_TIMESTAMP);