INSERT INTO status (status_id, status_name, entity_name, created_at)
VALUES
('PSV', 'SAVED', 'PAGE', CURRENT_TIMESTAMP),
('PPB', 'PUBLISHED', 'PAGE', CURRENT_TIMESTAMP),
('PSA', 'SAVED ARCHIVED', 'PAGE', CURRENT_TIMESTAMP),
('PPA', 'PUBLISHED ARCHIVED', 'PAGE', CURRENT_TIMESTAMP),

('NAC', 'ACTIVE', 'NOTEBOOK', CURRENT_TIMESTAMP),
('NAR', 'ARCHIVED', 'NOTEBOOK', CURRENT_TIMESTAMP),

('UAC', 'ACTIVE', 'USER', CURRENT_TIMESTAMP),
('UIA', 'INACTIVE', 'USER', CURRENT_TIMESTAMP);